
import matplotlib
import numpy as np
import os
import subprocess

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pylab

out_folder = './results/p_value_plots'
if not os.path.exists(out_folder):
    os.makedirs(out_folder)

point_list = []

for sim_thresh in np.arange(0.01, 0.51, 0.01):
# for sim_thresh in np.arange(0.01, 0.02, 0.01):
    command = 'python build_patient_feature_matrix.py 50 %g' % sim_thresh
    print command
    subprocess.call(command, shell=True)
    command = 'python subcategorize_patients.py kmeans 50 > %s/%g.txt' % (
        out_folder, sim_thresh)
    subprocess.call(command, shell=True)

    f = open('%s/%g.txt' % (out_folder, sim_thresh))
    for line in f:
        p_val = float(line.split()[1])
        point_list += [(sim_thresh, p_val)]
        break
    f.close()

plt.title('Survival plot p-value vs. cosine similarity lower bound')
plt.xlabel('Cosine Similarity Lower Bound')
plt.ylabel('p-value of Survival Plot')
plt.plot(*zip(*point_list))
# TODO: This is the best p-value of the survival curve generated by no-prosnet.
plt.axhline(0.0249887, color='r')
plt.ylim(0, 0.05)
plt.xlim(0, 0.5)
plt.show()

pylab.savefig('%s/p_val_plot.png' % out_folder)
plt.close()